package com.tepach.views;

import com.tepach.views.subview.Add_Miembro;
import java.awt.Font;
import javax.swing.JOptionPane;
import org.pushingpixels.substance.api.SubstanceLookAndFeel;
import org.pushingpixels.substance.api.skin.CremeCoffeeSkin;

/**
 *
 * @author Anthony Tepach
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
  
     Font fuentePrincipal;
    
    public App() {
        fuentePrincipal = new Font("/main/resources/imagen/gf-Regular.ttf", Font.TRUETYPE_FONT, 30);
        initComponents();
        setDefaultLookAndFeelDecorated(true);
        SubstanceLookAndFeel.setSkin("org.pushingpixels.substance.api.skin.CremeCoffeeSkin");
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jm_miembros = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jm_eventos = new javax.swing.JMenu();
        jm_familias = new javax.swing.JMenu();
        jm_ministerios = new javax.swing.JMenu();
        jm_cerrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ascender Iglesia");
        setFont(new java.awt.Font("Poiret One", 0, 14)); // NOI18N
        setIconImages(null);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setAlignmentX(0.0F);
        jDesktopPane1.setAlignmentY(0.0F);
        jDesktopPane1.setAutoscrolls(true);
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1240, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/banner.jpg"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, "card2");

        jMenuBar1.setFont(fuentePrincipal);

        jMenu1.setText("Ascender Iglesia");
        jMenu1.setEnabled(false);
        jMenu1.setFocusable(false);
        jMenuBar1.add(jMenu1);

        jm_miembros.setText("Agregar");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/015-add-friend.png"))); // NOI18N
        jMenuItem1.setText("Miembros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jm_miembros.add(jMenuItem1);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/016-remove-friend.png"))); // NOI18N
        jMenuItem3.setText("Invitados");
        jm_miembros.add(jMenuItem3);

        jMenuBar1.add(jm_miembros);

        jm_eventos.setText("Eventos");
        jMenuBar1.add(jm_eventos);

        jm_familias.setText("Familias");
        jMenuBar1.add(jm_familias);

        jm_ministerios.setText("Ministerios");
        jMenuBar1.add(jm_ministerios);

        jm_cerrar.setText("Cerrar");
        jm_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_cerrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jm_cerrar);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jm_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_cerrarMouseClicked
       int sino=JOptionPane.showConfirmDialog(rootPane,"¿Está seguro de salir?","Esperando confirmación",JOptionPane.YES_NO_OPTION);
        if (sino==0) {
            System.exit(sino);
        }
    }//GEN-LAST:event_jm_cerrarMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Add_Miembro addM=new Add_Miembro();
        jDesktopPane1.add(addM);
        addM.setLocation(1, 116);
        addM.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jm_cerrar;
    private javax.swing.JMenu jm_eventos;
    private javax.swing.JMenu jm_familias;
    private javax.swing.JMenu jm_miembros;
    private javax.swing.JMenu jm_ministerios;
    // End of variables declaration//GEN-END:variables
}
